# Generated by Django 5.0.7 on 2024-07-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
