# Generated by Django 5.0.7 on 2024-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_id_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
